# Generated by Django 4.2.4 on 2023-10-25 11:21

from django.db import migrations


def create_unique_brands(apps, schema_editor):
    shoe = apps.get_model('main_app', 'Shoe')
    unique_brands = apps.get_model('main_app', 'UniqueBrands')

    unique_brands_name = shoe.objects.values_list('brand', flat=True).distinct()

    unique_brands_for_create = [unique_brands(brand_name=name) for name in unique_brands_name]

    unique_brands.objects.bulk_create(unique_brands_for_create)

    # SECOND SOLUTION
    # for name in unique_brands_name:
    #     unique_brands.create(brand_name=name)


def delete_unique_brands(apps, schema_editor):
    unique_brands = apps.get_model('main_app', 'UniqueBrands')

    unique_brands.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_uniquebrands"),
    ]

    operations = [
        migrations.RunPython(create_unique_brands, reverse_code=delete_unique_brands)
    ]
