# Generated by Django 4.2.4 on 2023-10-27 17:45

from django.db import migrations


def set_price(apps, schema_editor):
    MULTIPLY_PRICE = 120

    smartphone_model = apps.get_model('main_app', 'SmartPhone')

    smartphones = smartphone_model.objects.all()

    for smartphone in smartphones:
        smartphone.price = len(smartphone.brand) * MULTIPLY_PRICE

    smartphone_model.objects.bulk_update(smartphones, ['price'])


def set_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'SmartPhone')

    smartphones = smartphone_model.objects.all()

    for smartphone in smartphones:
        if smartphone.price < 750:
            smartphone.category = 'Cheap'
        else:
            smartphone.category = 'Expensive'

    smartphone_model.objects.bulk_update(smartphones, ['category'])


def set_price_and_category(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


def set_price_and_category_default(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'SmartPhone')

    smartphones = smartphone_model.objects.all()

    price_default = smartphone_model._meta.get_field('price').default
    category_default = smartphone_model._meta.get_field('category').default

    for smartphone in smartphones:
        smartphone.price = price_default
        smartphone.category = category_default

    smartphone_model.objects.bulk_update(smartphones, ['price', 'category'])

class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0011_smartphone"),
    ]

    operations = [
        migrations.RunPython(set_price_and_category, reverse_code=set_price_and_category_default)
    ]
